"""add compute_resource_profiles table

Revision ID: c83b8d7c07e9
Revises: 637c57487a83
Create Date: 2026-07-30 10:47:25.288905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c83b8d7c07e9'
down_revision: Union[str, Sequence[str], None] = '637c57487a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('compute_resource_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('backend', sa.String(), nullable=False),
    sa.Column('k8s_kubeconfig', sa.String(), nullable=True),
    sa.Column('k8s_namespace', sa.String(), nullable=True),
    sa.Column('k8s_image', sa.String(), nullable=True),
    sa.Column('k8s_cpu', sa.String(), nullable=True),
    sa.Column('k8s_memory', sa.String(), nullable=True),
    sa.Column('k8s_gpu', sa.Integer(), nullable=True),
    sa.Column('slurm_host', sa.String(), nullable=True),
    sa.Column('slurm_port', sa.Integer(), nullable=True),
    sa.Column('slurm_username', sa.String(), nullable=True),
    sa.Column('slurm_ssh_private_key', sa.String(), nullable=True),
    sa.Column('slurm_partition', sa.String(), nullable=True),
    sa.Column('slurm_workdir', sa.String(), nullable=True),
    sa.Column('slurm_time_limit', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compute_resource_profiles_user_id'), 'compute_resource_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_compute_resource_profiles_user_id'), table_name='compute_resource_profiles')
    op.drop_table('compute_resource_profiles')
    # ### end Alembic commands ###
